---

# This play requires the following variable set
#   database_user: "<The user name that will be used to connect to the database>"
#   database_password: "<The password that will be used to connect to the database>"

- fail:
    msg: "database_user is required"
  when: database_user is not defined

- fail:
    msg: "database_password is required"
  when: database_password is not defined

- fail:
    msg: "database_root_password is required"
  when: database_root_password is not defined

- name: Start mariadb
  service:
    name: mariadb
    enabled: true
    state: started
  become: yes

- name: Setup root user
  community.mysql.mysql_user:
    login_user: "root"
    login_password: "{{ database_root_password }}"
    user: "root"
    password: "{{ database_root_password }}"
    check_implicit_admin: true
    host: localhost

- name: Remove remote root
  community.mysql.mysql_user:
    login_user: "root"
    login_password: "{{ database_root_password }}"
    user: "root"
    host: "{{ ansible_fqdn }}"
    check_implicit_admin: true
    state: absent

- name: Remove anonymous user on localhost
  community.mysql.mysql_user:
    login_user: "root"
    login_password: "{{ database_root_password }}"
    name: ""
    host: localhost
    state: absent

- name: Remove anonymous user on internal dns
  community.mysql.mysql_user:
    login_user: "root"
    login_password: "{{ database_root_password }}"
    name: ""
    host: "{{ ansible_fqdn }}"
    state: absent

- name: Create db user
  community.mysql.mysql_user:
    login_user: "root"
    login_password: "{{ database_root_password }}"
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    host: "%"
    priv: "*.*:ALL"
    state: present

